In [1]:
import polars as polas

In [3]:
bridge_job_skills =  polas.read_csv('../data/raw/bridge_job_skills.csv')

In [4]:
dim_company = polas.read_csv('../data/raw/dim_company.csv')

In [5]:
dim_country = polas.read_csv('../data/raw/dim_country.csv')

In [6]:
dim_platform = polas.read_csv('../data/raw/dim_platform.csv')

In [8]:
dim_skill = polas.read_csv('../data/raw/dim_skill.csv')

In [9]:
fact_job_postings = polas.read_csv('../data/raw/fact_job_postings.csv')

In [16]:
dim_company.n_unique()

20

In [24]:
def profile_dataframe(data):
    print("Dimensao: \n", data.shape)
    print("Colunas: \n",data.columns)
    print("Valores NUllos \n: ", data.null_count)
    print("Linhas unicas: \n", data.n_unique)
    print("Valores distintos \n", data.select(polas.all().n_unique()))

In [25]:
profile_dataframe(bridge_job_skills)

Dimensao:
 (247398, 2)
Colunas:
 ['job_id', 'skill']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (247_398, 2)
┌───────────┬──────────────────┐
│ job_id    ┆ skill            │
│ ---       ┆ ---              │
│ str       ┆ str              │
╞═══════════╪══════════════════╡
│ JOB-1     ┆ Data Engineering │
│ JOB-1     ┆ Redshift         │
│ JOB-1     ┆ TensorFlow       │
│ JOB-1     ┆ Airflow          │
│ JOB-2     ┆ Kafka            │
│ …         ┆ …                │
│ JOB-54999 ┆ GCP              │
│ JOB-55000 ┆ SQL              │
│ JOB-55000 ┆ Azure            │
│ JOB-55000 ┆ Redshift         │
│ JOB-55000 ┆ Airflow          │
└───────────┴──────────────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (247_398, 2)
┌───────────┬──────────────────┐
│ job_id    ┆ skill            │
│ ---       ┆ ---              │
│ str       ┆ str              │
╞═══════════╪══════════════════╡
│ JOB-1     ┆ Data Engineering │
│ JOB-1     ┆ Redshift         │
│ JOB-1     ┆ TensorFlow       │
│ JOB-1     ┆ Airflow          │
│ JOB-2     ┆ Kafka            │
│ …         ┆ …                │
│ JOB-54999 ┆ GCP              │
│ JOB-55000 ┆ SQL              │
│ JOB-55000 ┆ Azure            │
│ JOB-55000 ┆ Redshift         │
│ JOB-55000 ┆ Airflow          │
└───────────┴──────────────────┘>
Valores distintos
 shape: (1, 2)
┌────────┬───────┐
│ job_id ┆ skill │
│ ---    ┆ ---   │
│ u32    ┆ u32   │
╞════════╪═══════╡
│ 55000  ┆ 26    │
└────────┴───────┘

In [26]:
profile_dataframe(dim_company)

Dimensao:
 (20, 1)
Colunas:
 ['company']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (20, 1)
┌────────────┐
│ company    │
│ ---        │
│ str        │
╞════════════╡
│ Accenture  │
│ Airbnb     │
│ Amazon     │
│ Capgemini  │
│ Databricks │
│ …          │
│ Salesforce │
│ Snowflake  │
│ Stripe     │
│ TCS        │
│ Uber       │
└────────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (20, 1)
┌────────────┐
│ company    │
│ ---        │
│ str        │
╞════════════╡
│ Accenture  │
│ Airbnb     │
│ Amazon     │
│ Capgemini  │
│ Databricks │
│ …          │
│ Salesforce │
│ Snowflake  │
│ Stripe     │
│ TCS        │
│ Uber       │
└────────────┘>
Valores distintos
 shape: (1, 1)
┌─────────┐
│ company │
│ ---     │
│ u32     │
╞═════════╡
│ 20      │
└─────────┘

In [27]:
profile_dataframe(dim_country)

Dimensao:
 (13, 2)
Colunas:
 ['country', 'region']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (13, 2)
┌────────────────┬───────────────┐
│ country        ┆ region        │
│ ---            ┆ ---           │
│ str            ┆ str           │
╞════════════════╪═══════════════╡
│ United States  ┆ North America │
│ India          ┆ Asia          │
│ Germany        ┆ Europe        │
│ United Kingdom ┆ Europe        │
│ Canada         ┆ North America │
│ …              ┆ …             │
│ Ireland        ┆ Europe        │
│ UAE            ┆ Middle East   │
│ France         ┆ Europe        │
│ Spain          ┆ Europe        │
│ Brazil         ┆ South America │
└────────────────┴───────────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (13, 2)
┌────────────────┬───────────────┐
│ country        ┆ region        │
│ ---            ┆ ---           │
│ str            ┆ str           │
╞════════════════╪═══════════════╡
│ United States  ┆ North America │
│ India          ┆ Asia          │
│ Germany        ┆ Europe        │
│ United Kingdom ┆ Europe        │
│ Canada         ┆ North America │
│ …              ┆ …             │
│ Ireland        ┆ Europe        │
│ UAE            ┆ Middle East   │
│ France         ┆ Europe        │
│ Spain          ┆ Europe        │
│ Brazil         ┆ South America │
└────────────────┴───────────────┘>
Valores distintos
 shape: (1, 2)
┌─────────┬────────┐
│ country ┆ region │
│ ---     ┆ ---    │
│ u32     ┆ u32    │
╞═════════╪════════╡
│ 13      ┆ 6      │
└─────────┴────────┘

In [28]:
profile_dataframe(dim_platform)

Dimensao:
 (6, 1)
Colunas:
 ['platform']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (6, 1)
┌──────────────┐
│ platform     │
│ ---          │
│ str          │
╞══════════════╡
│ Company Site │
│ Glassdoor    │
│ Indeed       │
│ LinkedIn     │
│ Monster      │
│ Wellfound    │
└──────────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (6, 1)
┌──────────────┐
│ platform     │
│ ---          │
│ str          │
╞══════════════╡
│ Company Site │
│ Glassdoor    │
│ Indeed       │
│ LinkedIn     │
│ Monster      │
│ Wellfound    │
└──────────────┘>
Valores distintos
 shape: (1, 1)
┌──────────┐
│ platform │
│ ---      │
│ u32      │
╞══════════╡
│ 6        │
└──────────┘

In [29]:
profile_dataframe(dim_skill)

Dimensao:
 (26, 1)
Colunas:
 ['skill']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (26, 1)
┌──────────────────┐
│ skill            │
│ ---              │
│ str              │
╞══════════════════╡
│ AWS              │
│ Airflow          │
│ Azure            │
│ BigQuery         │
│ Data Engineering │
│ …                │
│ Spark            │
│ Statistics       │
│ Tableau          │
│ TensorFlow       │
│ dbt              │
└──────────────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (26, 1)
┌──────────────────┐
│ skill            │
│ ---              │
│ str              │
╞══════════════════╡
│ AWS              │
│ Airflow          │
│ Azure            │
│ BigQuery         │
│ Data Engineering │
│ …                │
│ Spark            │
│ Statistics       │
│ Tableau          │
│ TensorFlow       │
│ dbt              │
└──────────────────┘>
Valores distintos
 shape: (1, 1)
┌───────┐
│ skill │
│ ---   │
│ u32   │
╞═══════╡
│ 26    │
└───────┘

In [30]:
profile_dataframe(fact_job_postings)

Dimensao:
 (55000, 13)
Colunas:
 ['job_id', 'job_title', 'company', 'country', 'region', 'platform', 'experience_level', 'employment_type', 'salary_min_usd', 'salary_max_usd', 'remote_option', 'posting_date', 'applicants_estimate']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (55_000, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ job_id    ┆ job_title ┆ company   ┆ country   ┆ … ┆ salary_ma ┆ remote_op ┆ posting_d ┆ applican │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ x_usd     ┆ tion      ┆ ate       ┆ ts_estim │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ate      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ JOB-1     ┆ Senior    ┆ Netflix   ┆ Spain     ┆ … ┆ 171017    ┆ Hybrid    ┆ 52:59.3   ┆ 472      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-2     ┆ Data      ┆ Snowflake ┆ India     ┆ … ┆ 153462    ┆ Hybrid    ┆ 52:59.3   ┆ 500      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-3     ┆ Business  ┆ IBM       ┆ Netherlan ┆ … ┆ 121991    ┆ Onsite    ┆ 52:59.3   ┆ 34       │
│           ┆ Intellige ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│           ┆ nce       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-4     ┆ Data      ┆ Nvidia    ┆ Netherlan ┆ … ┆ 130952    ┆ Remote    ┆ 52:59.3   ┆ 26       │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-5     ┆ AI        ┆ Netflix   ┆ Germany   ┆ … ┆ 186131    ┆ Hybrid    ┆ 52:59.3   ┆ 303      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ JOB-54996 ┆ Senior    ┆ Salesforc ┆ Singapore ┆ … ┆ 155996    ┆ Onsite    ┆ 52:59.8   ┆ 287      │
│           ┆ Data      ┆ e         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54997 ┆ Analytics ┆ IBM       ┆ Spain     ┆ … ┆ 169687    ┆ Onsite    ┆ 52:59.8   ┆ 210      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54998 ┆ Data      ┆ Microsoft ┆ Netherlan ┆ … ┆ 120061    ┆ Hybrid    ┆ 52:59.8   ┆ 168      │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-54999 ┆ Senior    ┆ Uber      ┆ Brazil    ┆ … ┆ 97765     ┆ Hybrid    ┆ 52:59.8   ┆ 246      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-55000 ┆ Analytics ┆ Netflix   ┆ Germany   ┆ … ┆ 185136    ┆ Hybrid    ┆ 52:59.8   ┆ 226      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (55_000, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ job_id    ┆ job_title ┆ company   ┆ country   ┆ … ┆ salary_ma ┆ remote_op ┆ posting_d ┆ applican │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ x_usd     ┆ tion      ┆ ate       ┆ ts_estim │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ate      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ JOB-1     ┆ Senior    ┆ Netflix   ┆ Spain     ┆ … ┆ 171017    ┆ Hybrid    ┆ 52:59.3   ┆ 472      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-2     ┆ Data      ┆ Snowflake ┆ India     ┆ … ┆ 153462    ┆ Hybrid    ┆ 52:59.3   ┆ 500      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-3     ┆ Business  ┆ IBM       ┆ Netherlan ┆ … ┆ 121991    ┆ Onsite    ┆ 52:59.3   ┆ 34       │
│           ┆ Intellige ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│           ┆ nce       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-4     ┆ Data      ┆ Nvidia    ┆ Netherlan ┆ … ┆ 130952    ┆ Remote    ┆ 52:59.3   ┆ 26       │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-5     ┆ AI        ┆ Netflix   ┆ Germany   ┆ … ┆ 186131    ┆ Hybrid    ┆ 52:59.3   ┆ 303      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ JOB-54996 ┆ Senior    ┆ Salesforc ┆ Singapore ┆ … ┆ 155996    ┆ Onsite    ┆ 52:59.8   ┆ 287      │
│           ┆ Data      ┆ e         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54997 ┆ Analytics ┆ IBM       ┆ Spain     ┆ … ┆ 169687    ┆ Onsite    ┆ 52:59.8   ┆ 210      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54998 ┆ Data      ┆ Microsoft ┆ Netherlan ┆ … ┆ 120061    ┆ Hybrid    ┆ 52:59.8   ┆ 168      │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-54999 ┆ Senior    ┆ Uber      ┆ Brazil    ┆ … ┆ 97765     ┆ Hybrid    ┆ 52:59.8   ┆ 246      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-55000 ┆ Analytics ┆ Netflix   ┆ Germany   ┆ … ┆ 185136    ┆ Hybrid    ┆ 52:59.8   ┆ 226      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘>
Valores distintos
 shape: (1, 13)
┌────────┬───────────┬─────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ job_id ┆ job_title ┆ company ┆ country ┆ … ┆ salary_max_ ┆ remote_opti ┆ posting_da ┆ applicants │
│ ---    ┆ ---       ┆ ---     ┆ ---     ┆   ┆ usd         ┆ on          ┆ te         ┆ _estimate  │
│ u32    ┆ u32       ┆ u32     ┆ u32     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆           ┆         ┆         ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞════════╪═══════════╪═════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 55000  ┆ 10        ┆ 20      ┆ 13      ┆ … ┆ 45597       ┆ 3           ┆ 6          ┆ 596        │
└────────┴───────────┴─────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [32]:
profile_dataframe(fact_job_postings)

Dimensao:
 (55000, 13)
Colunas:
 ['job_id', 'job_title', 'company', 'country', 'region', 'platform', 'experience_level', 'employment_type', 'salary_min_usd', 'salary_max_usd', 'remote_option', 'posting_date', 'applicants_estimate']
Valores NUllos
:  <bound method DataFrame.null_count of shape: (55_000, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ job_id    ┆ job_title ┆ company   ┆ country   ┆ … ┆ salary_ma ┆ remote_op ┆ posting_d ┆ applican │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ x_usd     ┆ tion      ┆ ate       ┆ ts_estim │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ate      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ JOB-1     ┆ Senior    ┆ Netflix   ┆ Spain     ┆ … ┆ 171017    ┆ Hybrid    ┆ 52:59.3   ┆ 472      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-2     ┆ Data      ┆ Snowflake ┆ India     ┆ … ┆ 153462    ┆ Hybrid    ┆ 52:59.3   ┆ 500      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-3     ┆ Business  ┆ IBM       ┆ Netherlan ┆ … ┆ 121991    ┆ Onsite    ┆ 52:59.3   ┆ 34       │
│           ┆ Intellige ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│           ┆ nce       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-4     ┆ Data      ┆ Nvidia    ┆ Netherlan ┆ … ┆ 130952    ┆ Remote    ┆ 52:59.3   ┆ 26       │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-5     ┆ AI        ┆ Netflix   ┆ Germany   ┆ … ┆ 186131    ┆ Hybrid    ┆ 52:59.3   ┆ 303      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ JOB-54996 ┆ Senior    ┆ Salesforc ┆ Singapore ┆ … ┆ 155996    ┆ Onsite    ┆ 52:59.8   ┆ 287      │
│           ┆ Data      ┆ e         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54997 ┆ Analytics ┆ IBM       ┆ Spain     ┆ … ┆ 169687    ┆ Onsite    ┆ 52:59.8   ┆ 210      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54998 ┆ Data      ┆ Microsoft ┆ Netherlan ┆ … ┆ 120061    ┆ Hybrid    ┆ 52:59.8   ┆ 168      │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-54999 ┆ Senior    ┆ Uber      ┆ Brazil    ┆ … ┆ 97765     ┆ Hybrid    ┆ 52:59.8   ┆ 246      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-55000 ┆ Analytics ┆ Netflix   ┆ Germany   ┆ … ┆ 185136    ┆ Hybrid    ┆ 52:59.8   ┆ 226      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘>
Linhas unicas:
 <bound method DataFrame.n_unique of shape: (55_000, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ job_id    ┆ job_title ┆ company   ┆ country   ┆ … ┆ salary_ma ┆ remote_op ┆ posting_d ┆ applican │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ x_usd     ┆ tion      ┆ ate       ┆ ts_estim │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ate      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ JOB-1     ┆ Senior    ┆ Netflix   ┆ Spain     ┆ … ┆ 171017    ┆ Hybrid    ┆ 52:59.3   ┆ 472      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-2     ┆ Data      ┆ Snowflake ┆ India     ┆ … ┆ 153462    ┆ Hybrid    ┆ 52:59.3   ┆ 500      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-3     ┆ Business  ┆ IBM       ┆ Netherlan ┆ … ┆ 121991    ┆ Onsite    ┆ 52:59.3   ┆ 34       │
│           ┆ Intellige ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│           ┆ nce       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-4     ┆ Data      ┆ Nvidia    ┆ Netherlan ┆ … ┆ 130952    ┆ Remote    ┆ 52:59.3   ┆ 26       │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-5     ┆ AI        ┆ Netflix   ┆ Germany   ┆ … ┆ 186131    ┆ Hybrid    ┆ 52:59.3   ┆ 303      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ JOB-54996 ┆ Senior    ┆ Salesforc ┆ Singapore ┆ … ┆ 155996    ┆ Onsite    ┆ 52:59.8   ┆ 287      │
│           ┆ Data      ┆ e         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54997 ┆ Analytics ┆ IBM       ┆ Spain     ┆ … ┆ 169687    ┆ Onsite    ┆ 52:59.8   ┆ 210      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54998 ┆ Data      ┆ Microsoft ┆ Netherlan ┆ … ┆ 120061    ┆ Hybrid    ┆ 52:59.8   ┆ 168      │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-54999 ┆ Senior    ┆ Uber      ┆ Brazil    ┆ … ┆ 97765     ┆ Hybrid    ┆ 52:59.8   ┆ 246      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-55000 ┆ Analytics ┆ Netflix   ┆ Germany   ┆ … ┆ 185136    ┆ Hybrid    ┆ 52:59.8   ┆ 226      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘>
Valores distintos
 shape: (1, 13)
┌────────┬───────────┬─────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ job_id ┆ job_title ┆ company ┆ country ┆ … ┆ salary_max_ ┆ remote_opti ┆ posting_da ┆ applicants │
│ ---    ┆ ---       ┆ ---     ┆ ---     ┆   ┆ usd         ┆ on          ┆ te         ┆ _estimate  │
│ u32    ┆ u32       ┆ u32     ┆ u32     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆           ┆         ┆         ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞════════╪═══════════╪═════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 55000  ┆ 10        ┆ 20      ┆ 13      ┆ … ┆ 45597       ┆ 3           ┆ 6          ┆ 596        │
└────────┴───────────┴─────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [35]:
tables = {
    "fact_job_postings": fact_job_postings,
    "dim_company": dim_company,
    "dim_country": dim_country,
    "dim_platform": dim_platform,
    "dim_skill": dim_skill,
    "bridge_job_skills": bridge_job_skills,
}

In [43]:
for name, table in tables.items():  
    print(f"{name}: {table.shape}")

fact_job_postings: (55000, 13)
dim_company: (20, 1)
dim_country: (13, 2)
dim_platform: (6, 1)
dim_skill: (26, 1)
bridge_job_skills: (247398, 2)

In [44]:
tables.items()

dict_items([('fact_job_postings', shape: (55_000, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ job_id    ┆ job_title ┆ company   ┆ country   ┆ … ┆ salary_ma ┆ remote_op ┆ posting_d ┆ applican │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ x_usd     ┆ tion      ┆ ate       ┆ ts_estim │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ate      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ JOB-1     ┆ Senior    ┆ Netflix   ┆ Spain     ┆ … ┆ 171017    ┆ Hybrid    ┆ 52:59.3   ┆ 472      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-2     ┆ Data      ┆ Snowflake ┆ India     ┆ … ┆ 153462    ┆ Hybrid    ┆ 52:59.3   ┆ 500      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-3     ┆ Business  ┆ IBM       ┆ Netherlan ┆ … ┆ 121991    ┆ Onsite    ┆ 52:59.3   ┆ 34       │
│           ┆ Intellige ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│           ┆ nce       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-4     ┆ Data      ┆ Nvidia    ┆ Netherlan ┆ … ┆ 130952    ┆ Remote    ┆ 52:59.3   ┆ 26       │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-5     ┆ AI        ┆ Netflix   ┆ Germany   ┆ … ┆ 186131    ┆ Hybrid    ┆ 52:59.3   ┆ 303      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ JOB-54996 ┆ Senior    ┆ Salesforc ┆ Singapore ┆ … ┆ 155996    ┆ Onsite    ┆ 52:59.8   ┆ 287      │
│           ┆ Data      ┆ e         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54997 ┆ Analytics ┆ IBM       ┆ Spain     ┆ … ┆ 169687    ┆ Onsite    ┆ 52:59.8   ┆ 210      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-54998 ┆ Data      ┆ Microsoft ┆ Netherlan ┆ … ┆ 120061    ┆ Hybrid    ┆ 52:59.8   ┆ 168      │
│           ┆ Scientist ┆           ┆ ds        ┆   ┆           ┆           ┆           ┆          │
│ JOB-54999 ┆ Senior    ┆ Uber      ┆ Brazil    ┆ … ┆ 97765     ┆ Hybrid    ┆ 52:59.8   ┆ 246      │
│           ┆ Data      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Analyst   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ JOB-55000 ┆ Analytics ┆ Netflix   ┆ Germany   ┆ … ┆ 185136    ┆ Hybrid    ┆ 52:59.8   ┆ 226      │
│           ┆ Engineer  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘), ('dim_company', shape: (20, 1)
┌────────────┐
│ company    │
│ ---        │
│ str        │
╞════════════╡
│ Accenture  │
│ Airbnb     │
│ Amazon     │
│ Capgemini  │
│ Databricks │
│ …          │
│ Salesforce │
│ Snowflake  │
│ Stripe     │
│ TCS        │
│ Uber       │
└────────────┘), ('dim_country', shape: (13, 2)
┌────────────────┬───────────────┐
│ country        ┆ region        │
│ ---            ┆ ---           │
│ str            ┆ str           │
╞════════════════╪═══════════════╡
│ United States  ┆ North America │
│ India          ┆ Asia          │
│ Germany        ┆ Europe        │
│ United Kingdom ┆ Europe        │
│ Canada         ┆ North America │
│ …              ┆ …             │
│ Ireland        ┆ Europe        │
│ UAE            ┆ Middle East   │
│ France         ┆ Europe        │
│ Spain          ┆ Europe        │
│ Brazil         ┆ South America │
└────────────────┴───────────────┘), ('dim_platform', shape: (6, 1)
┌──────────────┐
│ platform     │
│ ---          │
│ str          │
╞══════════════╡
│ Company Site │
│ Glassdoor    │
│ Indeed       │
│ LinkedIn     │
│ Monster      │
│ Wellfound    │
└──────────────┘), ('dim_skill', shape: (26, 1)
┌──────────────────┐
│ skill            │
│ ---              │
│ str              │
╞══════════════════╡
│ AWS              │
│ Airflow          │
│ Azure            │
│ BigQuery         │
│ Data Engineering │
│ …                │
│ Spark            │
│ Statistics       │
│ Tableau          │
│ TensorFlow       │
│ dbt              │
└──────────────────┘), ('bridge_job_skills', shape: (247_398, 2)
┌───────────┬──────────────────┐
│ job_id    ┆ skill            │
│ ---       ┆ ---              │
│ str       ┆ str              │
╞═══════════╪══════════════════╡
│ JOB-1     ┆ Data Engineering │
│ JOB-1     ┆ Redshift         │
│ JOB-1     ┆ TensorFlow       │
│ JOB-1     ┆ Airflow          │
│ JOB-2     ┆ Kafka            │
│ …         ┆ …                │
│ JOB-54999 ┆ GCP              │
│ JOB-55000 ┆ SQL              │
│ JOB-55000 ┆ Azure            │
│ JOB-55000 ┆ Redshift         │
│ JOB-55000 ┆ Airflow          │
└───────────┴──────────────────┘)])

In [50]:
for name, table in  tables.items():
    print(f"{name}:  {table.shape} :  {table.columns}" )

fact_job_postings:  (55000, 13) :  ['job_id', 'job_title', 'company', 'country', 'region', 'platform', 'experience_level', 'employment_type', 'salary_min_usd', 'salary_max_usd', 'remote_option', 'posting_date', 'applicants_estimate']
dim_company:  (20, 1) :  ['company']
dim_country:  (13, 2) :  ['country', 'region']
dim_platform:  (6, 1) :  ['platform']
dim_skill:  (26, 1) :  ['skill']
bridge_job_skills:  (247398, 2) :  ['job_id', 'skill']

In [62]:
for name , table in tables.items():
    print(f"\n{'=' * 100}")
    print(f"\n Tabela : {name}")
    print(f"{'=' * 50}")
    print(f"dimensao", table.shape)
    print(f"colunas", table.columns)
    print("valores nulos")
    print(table.null_count())

====================================================================================================

 Tabela : fact_job_postings
==================================================
dimensao (55000, 13)
colunas ['job_id', 'job_title', 'company', 'country', 'region', 'platform', 'experience_level', 'employment_type', 'salary_min_usd', 'salary_max_usd', 'remote_option', 'posting_date', 'applicants_estimate']
valores nulos
shape: (1, 13)
┌────────┬───────────┬─────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ job_id ┆ job_title ┆ company ┆ country ┆ … ┆ salary_max_ ┆ remote_opti ┆ posting_da ┆ applicants │
│ ---    ┆ ---       ┆ ---     ┆ ---     ┆   ┆ usd         ┆ on          ┆ te         ┆ _estimate  │
│ u32    ┆ u32       ┆ u32     ┆ u32     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆           ┆         ┆         ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞════════╪═══════════╪═════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0      ┆ 0         ┆ 0       ┆ 0       ┆ … ┆ 0           ┆ 0           ┆ 0          ┆ 0          │
└────────┴───────────┴─────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

====================================================================================================

 Tabela : dim_company
==================================================
dimensao (20, 1)
colunas ['company']
valores nulos
shape: (1, 1)
┌─────────┐
│ company │
│ ---     │
│ u32     │
╞═════════╡
│ 0       │
└─────────┘

====================================================================================================

 Tabela : dim_country
==================================================
dimensao (13, 2)
colunas ['country', 'region']
valores nulos
shape: (1, 2)
┌─────────┬────────┐
│ country ┆ region │
│ ---     ┆ ---    │
│ u32     ┆ u32    │
╞═════════╪════════╡
│ 0       ┆ 0      │
└─────────┴────────┘

====================================================================================================

 Tabela : dim_platform
==================================================
dimensao (6, 1)
colunas ['platform']
valores nulos
shape: (1, 1)
┌──────────┐
│ platform │
│ ---      │
│ u32      │
╞══════════╡
│ 0        │
└──────────┘

====================================================================================================

 Tabela : dim_skill
==================================================
dimensao (26, 1)
colunas ['skill']
valores nulos
shape: (1, 1)
┌───────┐
│ skill │
│ ---   │
│ u32   │
╞═══════╡
│ 0     │
└───────┘

====================================================================================================

 Tabela : bridge_job_skills
==================================================
dimensao (247398, 2)
colunas ['job_id', 'skill']
valores nulos
shape: (1, 2)
┌────────┬───────┐
│ job_id ┆ skill │
│ ---    ┆ ---   │
│ u32    ┆ u32   │
╞════════╪═══════╡
│ 0      ┆ 0     │
└────────┴───────┘

In [63]:
for name, table in tables.items():
    print(f"{name} :  {table.is_duplicated().sum()} linhas duplicadas")

fact_job_postings :  0 linhas duplicadas
dim_company :  0 linhas duplicadas
dim_country :  0 linhas duplicadas
dim_platform :  0 linhas duplicadas
dim_skill :  0 linhas duplicadas
bridge_job_skills :  0 linhas duplicadas

In [68]:
for name, table in tables.items():
    print(f"{name} {table.null_count().sum()} valores nulos")

fact_job_postings shape: (1, 13)
┌────────┬───────────┬─────────┬─────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ job_id ┆ job_title ┆ company ┆ country ┆ … ┆ salary_max_ ┆ remote_opti ┆ posting_da ┆ applicants │
│ ---    ┆ ---       ┆ ---     ┆ ---     ┆   ┆ usd         ┆ on          ┆ te         ┆ _estimate  │
│ u32    ┆ u32       ┆ u32     ┆ u32     ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆           ┆         ┆         ┆   ┆ u32         ┆ u32         ┆ u32        ┆ u32        │
╞════════╪═══════════╪═════════╪═════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0      ┆ 0         ┆ 0       ┆ 0       ┆ … ┆ 0           ┆ 0           ┆ 0          ┆ 0          │
└────────┴───────────┴─────────┴─────────┴───┴─────────────┴─────────────┴────────────┴────────────┘ valores nulos
dim_company shape: (1, 1)
┌─────────┐
│ company │
│ ---     │
│ u32     │
╞═════════╡
│ 0       │
└─────────┘ valores nulos
dim_country shape: (1, 2)
┌─────────┬────────┐
│ country ┆ region │
│ ---     ┆ ---    │
│ u32     ┆ u32    │
╞═════════╪════════╡
│ 0       ┆ 0      │
└─────────┴────────┘ valores nulos
dim_platform shape: (1, 1)
┌──────────┐
│ platform │
│ ---      │
│ u32      │
╞══════════╡
│ 0        │
└──────────┘ valores nulos
dim_skill shape: (1, 1)
┌───────┐
│ skill │
│ ---   │
│ u32   │
╞═══════╡
│ 0     │
└───────┘ valores nulos
bridge_job_skills shape: (1, 2)
┌────────┬───────┐
│ job_id ┆ skill │
│ ---    ┆ ---   │
│ u32    ┆ u32   │
╞════════╪═══════╡
│ 0      ┆ 0     │
└────────┴───────┘ valores nulos

In [74]:
for name , table in tables.items():
    print(f"\n{'=' * 100}")
    print(f"Tabela: {name}")
    print(f"\n{'=' * 100}")
    print(table.schema)

====================================================================================================
Tabela: fact_job_postings

====================================================================================================
Schema({'job_id': String, 'job_title': String, 'company': String, 'country': String, 'region': String, 'platform': String, 'experience_level': String, 'employment_type': String, 'salary_min_usd': Int64, 'salary_max_usd': Int64, 'remote_option': String, 'posting_date': String, 'applicants_estimate': Int64})

====================================================================================================
Tabela: dim_company

====================================================================================================
Schema({'company': String})

====================================================================================================
Tabela: dim_country

====================================================================================================
Schema({'country': String, 'region': String})

====================================================================================================
Tabela: dim_platform

====================================================================================================
Schema({'platform': String})

====================================================================================================
Tabela: dim_skill

====================================================================================================
Schema({'skill': String})

====================================================================================================
Tabela: bridge_job_skills

====================================================================================================
Schema({'job_id': String, 'skill': String})

In [100]:
fact_job_postings.select(
    polas.col("job_title").value_counts(sort=True)
)

shape: (10, 1)
┌─────────────────────────────────┐
│ job_title                       │
│ ---                             │
│ struct[2]                       │
╞═════════════════════════════════╡
│ {"Business Intelligence Analys… │
│ {"AI Engineer",5595}            │
│ {"Senior Data Engineer",5584}   │
│ {"Senior Data Scientist",5572}  │
│ {"Analytics Engineer",5534}     │
│ {"Data Analyst",5506}           │
│ {"Data Engineer",5420}          │
│ {"Data Scientist",5408}         │
│ {"Machine Learning Engineer",5… │
│ {"Senior Data Analyst",5348}    │
└─────────────────────────────────┘

In [103]:
job_title_counts = (
    fact_job_postings
    .select(polas.col("job_title").value_counts(sort=True))
    .unnest("job_title")
)

job_title_counts

shape: (10, 2)
┌───────────────────────────────┬───────┐
│ job_title                     ┆ count │
│ ---                           ┆ ---   │
│ str                           ┆ u32   │
╞═══════════════════════════════╪═══════╡
│ Business Intelligence Analyst ┆ 5651  │
│ AI Engineer                   ┆ 5595  │
│ Senior Data Engineer          ┆ 5584  │
│ Senior Data Scientist         ┆ 5572  │
│ Analytics Engineer            ┆ 5534  │
│ Data Analyst                  ┆ 5506  │
│ Data Engineer                 ┆ 5420  │
│ Data Scientist                ┆ 5408  │
│ Machine Learning Engineer     ┆ 5382  │
│ Senior Data Analyst           ┆ 5348  │
└───────────────────────────────┴───────┘

In [105]:
company_counts = (
    fact_job_postings
    .select(
        polas.col("company").value_counts(
            sort=True,
            name="count"
        )
    )
    .unnest("company")
)

company_counts

shape: (20, 2)
┌────────────┬───────┐
│ company    ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ Salesforce ┆ 2811  │
│ Infosys    ┆ 2806  │
│ TCS        ┆ 2802  │
│ SAP        ┆ 2801  │
│ Uber       ┆ 2799  │
│ …          ┆ …     │
│ Accenture  ┆ 2695  │
│ Airbnb     ┆ 2693  │
│ Amazon     ┆ 2691  │
│ Google     ┆ 2689  │
│ Nvidia     ┆ 2681  │
└────────────┴───────┘

In [ ]:
jobs_by_country_and_level = (
    fact_job_postings
    .group_by(["country", "experience_level"])
    .agg(polas.len().alias("job_count"))
    .sort("job_count", descending=True))

jobs_by_country_and_level

NameError: name 'alias' is not defined